/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "us-east-1",
    "aws_cognito_identity_pool_id": "us-east-1:deda1bbf-f781-42b8-9842-b0a4819a5a2b",
    "aws_cognito_region": "us-east-1",
    "aws_user_pools_id": "us-east-1_gFzYmxNpP",
    "aws_user_pools_web_client_id": "7ipkpamobi68uod27b8gtp4lj",
    "oauth": {}
};


export default awsmobile;
 